name: Deploy to Vertex AI Notebooks

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          

      - name: Copy data to GCS
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'notebooks'
          destination: 'poc-buck'

      - name: Copy code from GCS to Vertex AI notebook
        run: |
          # Replace "your-bucket" with the name of your GCS bucket
          # Replace "your-code-folder" with the path to the code folder within the GCS bucket
          # Replace "your-project-id" with your GCP project ID
          # Replace "your-notebook-name" with the name of your Vertex AI notebook instance
          
          gsutil cp -r gs://poc-buck/notebooks/ /tmp/notebook

      - name: Upload code to Vertex AI Platform
        run: |
          # Replace "your-model" with the name of your model in the Vertex AI Platform
          # Replace "your-version" with the version of the model
          # Replace "your-code-folder" with the path to the code folder within the GCS bucket
          gcloud ai custom-jobs upload-code /tmp/notebooks


