name: Deploy to Vertex AI Notebooks

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          

      - name: Copy code to GCS bucket
        run: |
          # Replace "your-bucket" with the name of your GCS bucket
          gsutil cp -r notebooks/ gs://misc_data_bucket_gcp/
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Vertex AI Notebook 1
        run: |
          gcloud ai notebooks instances update ${{ secrets.INSTANCE_NAME }} \
            --update-labels=script=/content/code/main.py

